[package]
name = "tools-mcp-local"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
glob.workspace = true
ignore.workspace = true
memchr.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tree-sitter.workspace = true
tree-sitter-cpp.workspace = true
tools-mcp-core = { path = "../tools-mcp-core" }

[dev-dependencies]
tempfile.workspace = true

[[bench]]
name = "read_file"
harness = false
